name: Vagrant provision the homelab
on:
    push:
        branches:
            - "master"
jobs:
    deploy:
        runs-on: self-hosted
        steps:
          - name: Checkout
            uses: actions/checout@v2
          - name: create kind cluster
            run: kind create cluster --config ./kindCluster/kind-example-config.yaml
